# Generated by Django 5.2.8 on 2025-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                (
                    "importance",
                    models.IntegerField(
                        default=5, help_text="Scale of 1-10, where 10 is most important"
                    ),
                ),
                (
                    "estimated_hours",
                    models.IntegerField(
                        default=1, help_text="Estimated time to complete in hours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "dependencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of task IDs that this task depends on",
                    ),
                ),
            ],
        ),
    ]
